apiVersion: v1
kind: Service
metadata:
    name: evaluation-runner-service
    namespace: gaslight-production
spec:
    type: ClusterIP
    selector:
        app: evaluation-runner-deployment
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 5000
