apiVersion: batch/v1
kind: CronJob
metadata:
  name: tournament-runner-production
  namespace: gaslight-staging
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: tournament-runner-production
        spec:
          restartPolicy: OnFailure
          automountServiceAccountToken: false
          containers:
            - name: tournament-runner-production
              image: "rhaversen/gaslight-code-runner:3939c36e090fb19cb4e835c9c7504c73d37ff821"
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "400m"
                  memory: "300M"
                requests:
                  cpu: "250m"
                  memory: "200M"
              envFrom:
                - secretRef:
                    name: tournament-runner-secrets
