apiVersion: apps/v1
kind: Deployment
metadata:
    name: evaluation-runner-deployment
    namespace: gaslight-staging
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: evaluation-runner-deployment
    template:
        metadata:
            labels:
                app: evaluation-runner-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: evaluation-runner-deployment
                    resources:
                        limits:
                            cpu: "400m"
                            memory: "300M"
                        requests:
                            cpu: "250m"
                            memory: "200M"
                    image: "rhaversen/gaslight-code-runner:10356678106eef67bd4f0d6652b87e4f18f7cf41"
                    imagePullPolicy: Always
                    livenessProbe:
                        httpGet:
                            path: api/service/livez
                            port: 5000
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    readinessProbe:
                        httpGet:
                            path: api/service/readyz
                            port: 5000
                        periodSeconds: 10
                        initialDelaySeconds: 15
                        failureThreshold: 5
                    ports:
                        -   containerPort: 5000
                    envFrom:
                        -   secretRef:
                                name: evaluation-runner-secrets
