apiVersion: v1
kind: Service
metadata:
    name: code-runner-service
    namespace: gaslight-production
spec:
    type: ClusterIP
    selector:
        app: code-runner
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 5000
